=== hazimt/myBranch/XML/XML/Week3/Assignment03/Review_pg132/hw.dtd
<!--
   New Perspectives on XML
   Tutorial 3
   Review Assignment

   Hardware list DTD
   Author: Hazim Mohaisen
   Date:   05/15/2012

   Filename:         hw.dtd
   Supporting Files: 
-->

<!ELEMENT hlist (hardware+)>
<!ELEMENT hardware (model, manufacturer, mPrice)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT mPrice (#PCDATA)>
<!ATTLIST model MID ID #REQUIRED>
<!ATTLIST model category (Camera | Scanner | Tablet) #REQUIRED>
<!ATTLIST model sBundle IDREF #IMPLIED>

=== hazimt/myBranch/XML/XML/Week3/Assignment03/Review_pg132/hwlist.xml
<!--
   New Perspectives on XML
   Tutorial 3
   Review Assignment

   List of hardware products
   Author: Hazim Mohaisen
   Date:   05/15/2012 

   Filename:         hwlist.xml
   Supporting Files: 
-->

<!--
<!DOCTYPE hlist SYSTEM "hw.dtd">
-->

<hlist>
   <hardware>
      <model MID="DCT5" category="Camera">Digital Camera 5 Mpx</model>
      <manufacturer>Tapan Inc.</manufacturer>
      <mPrice>599.95</mPrice>
   </hardware>
   <hardware>
      <model MID="DCT7" category="Camera" sBundle="PS50W">Digital Camera 7 Mpx</model>
      <manufacturer>Tapan Inc.</manufacturer>
      <mPrice>749.50</mPrice>
   </hardware>
   <hardware>
      <model MID="DCT5Z" category="Camera">Digital Camera 5 Mpx -zoom</model>
      <manufacturer>Tapan Inc.</manufacturer>
      <mPrice>699.95</mPrice>
   </hardware>
   <hardware>
      <model MID="DCT7Z" category="Camera" sBundle="PA80W">Digital Camera 7 Mpx -zoom</model>
      <manufacturer>Tapan Inc.</manufacturer>
      <mPrice>889.50</mPrice>
   </hardware>
   <hardware>
      <model MID="SCL4C" category="Scanner" sBundle="SMT30W">Flatbed Scanner 4C</model>
      <manufacturer>Linton Inc.</manufacturer>
      <mPrice>177.99</mPrice>
   </hardware>
   <hardware>
      <model MID="SCL4CII" category="Scanner" sBundle="SMT30W">Flatbed Scanner 4CII</model>
      <manufacturer>Linton Inc.</manufacturer>
      <mPrice>228.29</mPrice>
   </hardware>
   <hardware>
      <model MID="LDT" category="Tablet">Digital Tablet</model>
      <manufacturer>Linton Inc.</manufacturer>
      <mPrice>129.50</mPrice>
   </hardware>
</hlist>
