=== hazimt/myBranch/XML/XML/Week7/Assignment04/Case4_p_221/Ventian/music.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
   New Perspectives on XML
   Tutorial 4
   Case Problem 1

   Jazz Warehouse Vintage Albums Schema
   Author: Hazim Mohaisen
   Date:   05/30/2012

   Filename:         music.xsd
   Supporting Files: 
 
-->
<!-- Are lines 2 and 3 needed? -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://mediamart.com/music"
             targetNamespace="http://mediamart.com/music">

  <!-- definitions of simple types -->
  <!--Decalre the genreType custom type-->
  <xsd:simpleType name="genreType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Rock"/>
      <xsd:enumeration value="Jazz"/>
      <xsd:enumeration value="Opera"/>
      <xsd:enumeration value="Classical"/>
    </xsd:restriction>
  </xsd:simpleType>

  <!--Declare the formatType custom type-->
  <xsd:simpleType name="formatType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="Cassette"/>
      <xsd:enumeration value="CD"/>
    </xsd:restriction>
  </xsd:simpleType>

  <!--Declare the priceType custom type-->
  <xsd:simpleType name="priceType">
    <xsd:restriction base="xsd:string">
      <!--http://docs.limesurvey.org/Using+regular+expressions&structure=Deutsche+Anleitung+f%C3%BCr+LimeSurvey-->
      <!--(translation: from the beginning (^) match only numbers for however many there are, at least one, optionally followed by a group containing a decimal and two more numbers before the end of the string ($))-->
      <!--^\$?\d+(\.(\d{2}))?$-->
      <!--xsd:pattern value="^$[0-9]+(\.[0-9]{2})?$"/-->
      <!--xsd:pattern value="^\$?\d+(\.(\d{2}))?$"/-->
      <!--xsd:pattern value="^\$?\d{1,2}.\d{1,2}"/-->
      <!-- This works in Visual Studio but NOT in Exchanger XML!!!!-->
      <xsd:pattern value="^\$?\d{1,2}.\d{1,2}"/>
    </xsd:restriction>
  </xsd:simpleType>

  <!--Declare the priceType custom type-->
  <xsd:simpleType name="priceType1">
    <xsd:restriction base="xsd:string">
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="music">
    <xsd:complexType>
      <xsd:sequence>

        <xsd:element name="album" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <!-- Declare album elements -->
              <xsd:element name="artist" type="xsd:string"/>
              <xsd:element name="title" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
            <!-- Declare album attributes -->
            <xsd:attribute name="genre" type="genreType" use="required"/>
            <xsd:attribute name="format" type="formatType" use="required"/>
            <xsd:attribute name="price" type="priceType1" use="required"/>
          </xsd:complexType>
        </xsd:element>

      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== hazimt/myBranch/XML/XML/Week7/Assignment04/Case4_p_221/Ventian/music.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   New Perspectives on XML
   Tutorial 4
   Case Problem 4

   MediaMart Online Music
   Author: Hazim Mohaisen
   Date:   05/30/2012

-->
<mu:music xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:mu="http://mediamart.com/music"
       xsi:schemaLocation="http://mediamart.com/music music.xsd">

   <album genre = "Rock" format = "Cassette" price = "$12.95" >
      <artist>The Beatles</artist>
       <title>Abbey Road</title>
   </album>

   <album genre = "Rock" format = "CD" price = "$14.95">
      <artist>The Beatles</artist>
       <title>The White Album</title>
   </album>

   <album genre = "Jazz" format = "CD" price = "$11.50">
      <artist>Mile Davis</artist>
       <title>Cookin'</title>
   </album>

   <album genre = "Opera" format = "CD" price = "$29.95">
      <artist>Richard Wagner</artist>
       <title>Das Rheingold</title>
   </album>

   <album genre = "Rock" format = "Cassette" price = "$14.95">
      <artist>Jethro Tull</artist>
       <title>Stand Up</title>
   </album>

   <album genre = "Classical" format = "CD" price = "$17.48">
      <artist>Richard Strauss</artist>
       <title>Wind Concertos</title>
   </album>

   <album genre = "Classical" format = "CD" price = "$21.55">
      <artist>Antonin Dvorak</artist>
       <title>The 8th Symphony</title>
   </album>

   <album genre = "Rock" format = "Cassette" price = "$14.95">
      <artist>The Police</artist>
       <title>The Police</title>
   </album>

   <album genre = "Jazz" format = "CD" price = "$19.95">
      <artist>Duke Ellington</artist>
       <title>Live at Newport</title>
   </album>

   <album genre = "Classical" format = "CD" price = "$11.95">
      <artist>Carl Orff</artist>
       <title>Carmina Burana</title>
   </album>

   <album genre = "Opera" format = "CD" price = "$29.95">
      <artist>Giuseppe Verdi</artist>
       <title>Aida</title>
   </album>


</mu:music>
