<?xml version="1.0"?>

<!-- File Name: Inventory Valid.xml -->

<!DOCTYPE INVENTORY
   [
   <!ELEMENT INVENTORY (BOOK)*>

   <!ELEMENT BOOK (TITLE, AUTHOR, BINDING, PAGES, PRICE)> 
   <!ATTLIST BOOK   InStock (yes|no) #REQUIRED>

   <!ELEMENT TITLE (#PCDATA | SUBTITLE)*>

   <!ELEMENT SUBTITLE (#PCDATA)>

   <!ELEMENT AUTHOR (#PCDATA)>
   <!ATTLIST AUTHOR   Born CDATA #IMPLIED>

   <!ELEMENT BINDING (#PCDATA)>

   <!ELEMENT PAGES (#PCDATA)>

   <!ELEMENT PRICE (#PCDATA)>
   ]
>

<INVENTORY>
   <BOOK InStock="yes">
      <TITLE>The Adventures of Huckleberry Finn</TITLE>
      <AUTHOR Born="1835">Mark Twain</AUTHOR>
      <BINDING>mass market paperback</BINDING>
      <PAGES>298</PAGES>
      <PRICE>$5.49</PRICE>
   </BOOK>
   <BOOK InStock="no">
      <TITLE>Leaves of Grass</TITLE>
      <AUTHOR Born="1819">Walt Whitman</AUTHOR>
      <BINDING>hardcover</BINDING>
      <PAGES>462</PAGES>
      <PRICE>$7.75</PRICE>
   </BOOK>
   <BOOK InStock="yes">
      <TITLE>The Legend of Sleepy Hollow</TITLE>
      <AUTHOR>Washington Irving</AUTHOR>
      <BINDING>mass market paperback</BINDING>
      <PAGES>98</PAGES>
      <PRICE>$2.95</PRICE>
   </BOOK>
   <BOOK InStock="yes">
      <TITLE>The Marble Faun</TITLE>
      <AUTHOR Born="1804">Nathaniel Hawthorne</AUTHOR>
      <BINDING>trade paperback</BINDING>
      <PAGES>473</PAGES>
      <PRICE>$10.95</PRICE>
   </BOOK>
   <BOOK InStock="no">
      <TITLE>Moby-Dick
         <SUBTITLE>Or, the Whale</SUBTITLE>
      </TITLE>
      <AUTHOR Born="1819">Herman Melville</AUTHOR>
      <BINDING>hardcover</BINDING>
      <PAGES>724</PAGES>
      <PRICE>$9.95</PRICE>
   </BOOK>
   <BOOK InStock="yes">
      <TITLE>The Portrait of a Lady</TITLE>
      <AUTHOR>Henry James</AUTHOR>
      <BINDING>mass market paperback</BINDING>
      <PAGES>256</PAGES>
      <PRICE>$4.95</PRICE>
   </BOOK>
   <BOOK InStock="yes">
      <TITLE>The Scarlet Letter</TITLE>
      <AUTHOR>Nathaniel Hawthorne</AUTHOR>
      <BINDING>trade paperback</BINDING>
      <PAGES>253</PAGES>
      <PRICE>$4.25</PRICE>
   </BOOK>
   <BOOK InStock="no">
      <TITLE>The Turn of the Screw</TITLE>
      <AUTHOR>Henry James</AUTHOR>
      <BINDING>trade paperback</BINDING>
      <PAGES>384</PAGES>
      <PRICE>$3.35</PRICE>
   </BOOK>
</INVENTORY>
