<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!--
   New Perspectives on XML
   Tutorial 3
   Tutorial Case

   Pixal Products order Report
   Author: hazim
   Date:   4/17/2012

   Filename:         order.xml
   Supporting Files: codes.dtd
-->

<!--  Here we are creating the DTD (i.e template) for our own xml file below.  
That is why you see customers, names ...etc .  
In the DTD try to be most specific you don't want to go too much into details. -->

<!DOCTYPE customers
[
  <!-- The 
    + means we will have at least one customer, 
    * means pretty relaxed we might have 0 or infinity customers, 
    ? we may have customers or 0 or 1-->
  <!ELEMENT customers (customer+)>

  <!-- Listed the child elements -->
  <!-- either phone or email -->
  <!-- <!ELEMENT customer (name, address, (phone | email?), orders)> -->
  <!-- It could be pcdata or name-->
  <!-- <!ELEMENT customer (#PCDATA|name)> -->
  <!ELEMENT customer (name, address, phone, email?, orders)>

  <!ATTLIST customer custID ID #REQUIRED>
  <!ATTLIST customer custType (home | business) #IMPLIED> 

  <!--PCDATA is a general text that can be parsed with the regular parser. in other words text without tags.  
      But the following can't be part of DTD data like < or > or &.  It stands for Parsed Character DATA-->
    <!ELEMENT name (#PCDATA)>
      <!-- enumeration of options so options are Mr, mrs, Ms.  And it's NOT required i.e implied-->
      <!ATTLIST name title (Mr. | Mrs. | Ms.) #IMPLIED>

  <!ELEMENT address (#PCDATA)>
    <!ELEMENT phone (#PCDATA)>
    <!ELEMENT email (#PCDATA)>

    <!-- without the plus it says Only one order can exist in the document.  So we need the plus.  otherwise the error msg: 
          [Xerces-J 2.9.1] Validating "ordertxt.xml" against "Internal DocType Declaration" ...
          Ln 90 Col 16 - The content of element type "orders" must match "(order)".
          1 Errors
-->
    <!ELEMENT orders (order+)>
    <!ELEMENT order (orderDate, items)>
      <!ATTLIST order orderID ID #REQUIRED>
      <!ATTLIST order orderBy IDREF #REQUIRED>

    <!ELEMENT orderDate (#PCDATA)>

    <!ELEMENT items (item+)>
      <!ELEMENT item (#PCDATA)>
        <!ATTLIST item itemPrice CDATA #REQUIRED>
        <!-- If attribute not present it's assumed to be one-->
        <!ATTLIST item itemQty CDATA "1">
]
>

<customers>
   <customer custID="cust201" custType="home">
      <name title="Mr.">David Lynn</name>
      <address>
        <!-- unparsed data. stands for Character Data-->
         <![CDATA[                    
         211 Fox Street
         Greenville, NH 80021
         ]]>
      </address>
      <phone>(315) 555-1812</phone>
      <email>dlynn@nhs.net</email>
      <orders>
         <order orderID="or10311" orderBy="cust201">
            <orderDate>8/1/2008</orderDate>
            <items>
               <item itemPrice="599.95">DCT5Z</item>
               <item itemPrice="199.95">SM128</item>
               <item itemPrice="29.95" itemQty="2">RCL</item>
            </items>
         </order>
         <order orderID="or11424" orderBy="cust201">
            <orderDate>9/14/2008</orderDate>
            <items>
               <item itemPrice="59.95">BCE4L</item>
            </items>
         </order>
      </orders>
   </customer>

   <customer custID="cust202">
      <name title="Mrs.">Jean Kaufmann</name>
      <address>
         <![CDATA[
         411 East Oak Avenue
         Cashton, MI  20401
         ]]>
      </address>
      <phone>(611) 555-4033</phone>
      <email>JKaufmann@cshweb.com</email>
      <orders>
         <order orderID="or10899" orderBy="cust202">
            <orderDate>8/11/2008</orderDate>
            <items>
               <item itemPrice="59.99">WBC500</item>
               <item itemPrice="5.95" itemQty="2">RCA</item>
            </items>
         </order>
      </orders>
   </customer>

   <customer custID="cust203" custType="business">
      <name>AdServices</name>
      <address>
         <![CDATA[
         55 Washburn Lane
         Creighton, UT  98712
         ]]>
      </address>
      <phone>(811) 555-2987</phone>
      <orders>
         <order orderID="or11201" orderBy="cust203">
            <orderDate>9/15/2008</orderDate>
            <items>
               <item itemPrice="179.99" itemQty="3">SCL4C</item>
            </items>
         </order>
      </orders>
   </customer>
</customers>